import 'package:audio_learning_app/models/learning_object_v2.dart';
import 'package:audio_learning_app/models/word_timing.dart';
import 'package:audio_learning_app/models/sentence_timing.dart';
import 'package:audio_learning_app/models/content_metadata.dart';

class TestData {
  static LearningObjectV2 createTestLearningObjectV2({
    String? id,
    String? assignmentId,
    String? courseId,
    String? title,
    int? orderIndex,
    String? displayText,
    List<String>? paragraphs,
    List<String>? headers,
    ContentFormatting? formatting,
    ContentMetadata? metadata,
    List<WordTiming>? wordTimings,
    List<SentenceTiming>? sentenceTimings,
    int? totalDurationMs,
    String? audioUrl,
    int? audioSizeBytes,
    String? audioFormat,
    int? fileVersion,
    DateTime? createdAt,
    DateTime? updatedAt,
    bool? isCompleted,
    bool? isInProgress,
    int? currentPositionMs,
    int? lastWordIndex,
    int? lastSentenceIndex,
    double? playbackSpeed,
  }) {
    return LearningObjectV2(
      id: id ?? 'test-lo-id',
      assignmentId: assignmentId ?? 'test-assignment-id',
      courseId: courseId ?? 'test-course-id',
      title: title ?? 'Test Learning Object',
      orderIndex: orderIndex ?? 0,
      displayText: displayText ?? 'This is a test learning object.',
      paragraphs: paragraphs ?? ['This is a test learning object.'],
      headers: headers ?? ['Test Header'],
      formatting: formatting ?? ContentFormatting(
        boldHeaders: false,
        paragraphSpacing: true,
      ),
      metadata: metadata ?? ContentMetadata(
        wordCount: 6,
        characterCount: 32,
        estimatedReadingTime: '1 second',
        language: 'en',
      ),
      wordTimings: wordTimings ?? [
        WordTiming(
          word: 'This',
          startMs: 0,
          endMs: 500,
          sentenceIndex: 0,
          charStart: 0,
          charEnd: 4,
        ),
        WordTiming(
          word: 'is',
          startMs: 500,
          endMs: 800,
          sentenceIndex: 0,
          charStart: 5,
          charEnd: 7,
        ),
        WordTiming(
          word: 'a',
          startMs: 800,
          endMs: 1000,
          sentenceIndex: 0,
          charStart: 8,
          charEnd: 9,
        ),
        WordTiming(
          word: 'test',
          startMs: 1000,
          endMs: 1500,
          sentenceIndex: 0,
          charStart: 10,
          charEnd: 14,
        ),
        WordTiming(
          word: 'learning',
          startMs: 1500,
          endMs: 2000,
          sentenceIndex: 0,
          charStart: 15,
          charEnd: 23,
        ),
        WordTiming(
          word: 'object.',
          startMs: 2000,
          endMs: 2500,
          sentenceIndex: 0,
          charStart: 24,
          charEnd: 31,
        ),
      ],
      sentenceTimings: sentenceTimings ?? [
        SentenceTiming(
          text: 'This is a test learning object.',
          startMs: 0,
          endMs: 2500,
          sentenceIndex: 0,
          wordStartIndex: 0,
          wordEndIndex: 5,
          charStart: 0,
          charEnd: 31,
        ),
      ],
      totalDurationMs: totalDurationMs ?? 2500,
      audioUrl: audioUrl ?? 'https://example.com/test-audio.mp3',
      audioSizeBytes: audioSizeBytes ?? 1024000,
      audioFormat: audioFormat ?? 'mp3',
      fileVersion: fileVersion ?? 1,
      createdAt: createdAt ?? DateTime.now(),
      updatedAt: updatedAt ?? DateTime.now(),
      isCompleted: isCompleted,
      isInProgress: isInProgress,
      currentPositionMs: currentPositionMs,
      lastWordIndex: lastWordIndex,
      lastSentenceIndex: lastSentenceIndex,
      playbackSpeed: playbackSpeed,
    );
  }
}