name: audio_learning_app
description: A Flutter-based mobile application that streams narrated audio of educational content with synchronized dual-level word and sentence highlighting.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Audio
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  audio_service: ^0.18.12
  
  # Authentication
  amplify_flutter: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  
  # Backend
  supabase_flutter: ^2.3.0
  
  # HTTP & Network
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  
  # Stream Processing
  rxdart: ^0.27.7
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.1
  
  # UI Components
  cupertino_icons: ^1.0.5
  google_fonts: ^6.1.0

  # Environment Configuration
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/test_content/learning_objects/63ad7b78-0970-4265-a4fe-51f3fee39d5f/
