name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  FLUTTER_VERSION: "3.35.3"

jobs:
  # Quick validation for PRs
  validate-pr:
    name: Validate PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze --no-fatal-infos

      - name: Run tests
        run: flutter test

      - name: PR Status
        if: always()
        run: |
          echo "## PR Validation Complete"
          echo "✅ All checks passed" || echo "❌ Some checks failed"